/**
 * Reads a .pptx generated by this app back into the editor model.
 *
 * Shapes, text boxes and groups are parsed from the slide OOXML (the subset
 * the exporter emits). Charts are restored from the re-edit metadata that
 * rides on each chart: the `a:extLst` on the shape's `p:cNvPr` (primary),
 * or — for image-exported charts — the iTXt chunk inside the PNG itself.
 */
import { A, DC, P, PmlPackage, R, XElement, type OpenXmlPart } from "openxmlsdkts";

import { SHAPE_DEFINITIONS } from "@/features/editor/shape-defs";
import {
  createId,
  createSlide,
  createTextContent,
  type ChartObject,
  type Deck,
  type GroupObject,
  type LeafObject,
  type ShapeKind,
  type ShapeObject,
  type Slide,
  type SlideObject,
  type TextContent,
  type TextHAlign,
  type TextObject,
  type TextVAlign,
} from "@/features/editor/types";

import { base64ToBytes } from "./binary";
import { readPngTextChunk } from "./png-text";
import { EMU_PER_PX } from "./pptx";
import { PNG_TEXT_KEYWORD, readChartMeta } from "./pptx/chart-meta";

export class PptxImportError extends Error {}

const UNSUPPORTED_FILE = "このアプリで書き出した PPTX ファイルのみ読み込めます";

function emuToPx(value: string | undefined): number {
  return Math.round(Number(value ?? 0) / EMU_PER_PX);
}

const PRST_TO_SHAPE_KIND = new Map<string, ShapeKind>(
  SHAPE_DEFINITIONS.map((definition) => [definition.presetGeometry, definition.kind]),
);

const ALIGN_FROM_OOXML: Record<string, TextHAlign> = {
  l: "left",
  ctr: "center",
  r: "right",
  just: "justify",
};

const ANCHOR_FROM_OOXML: Record<string, TextVAlign> = {
  t: "top",
  ctr: "center",
  b: "bottom",
};

function hexColor(srgbClr: XElement | null | undefined): string | undefined {
  const value = srgbClr?.attribute("val")?.value;
  return value ? `#${value.toLowerCase()}` : undefined;
}

function solidFillColor(container: XElement | null | undefined): string | undefined {
  return hexColor(container?.element(A.solidFill)?.element(A.srgbClr));
}

interface ParsedFrame {
  x: number;
  y: number;
  width: number;
  height: number;
}

function parseXfrm(xfrm: XElement | null | undefined, context: string): ParsedFrame {
  const off = xfrm?.element(A.off);
  const ext = xfrm?.element(A.ext);
  if (!off || !ext) {
    throw new PptxImportError(`${UNSUPPORTED_FILE} (${context} の座標情報がありません)`);
  }
  return {
    x: emuToPx(off.attribute("x")?.value),
    y: emuToPx(off.attribute("y")?.value),
    width: emuToPx(ext.attribute("cx")?.value),
    height: emuToPx(ext.attribute("cy")?.value),
  };
}

function parseTextContent(txBody: XElement | null | undefined): TextContent {
  const content = createTextContent();
  if (!txBody) {
    return content;
  }
  const anchor = txBody.element(A.bodyPr)?.attribute("anchor")?.value;
  if (anchor && ANCHOR_FROM_OOXML[anchor]) {
    content.verticalAlign = ANCHOR_FROM_OOXML[anchor];
  }
  const paragraphs = txBody.elements(A.p);
  content.text = paragraphs
    .map((paragraph) =>
      paragraph
        .elements(A.r)
        .map((run) => run.element(A.t)?.value ?? "")
        .join(""),
    )
    .join("\n")
    // The exporter writes a single empty paragraph for empty text.
    .replace(/^\n?$/, "");

  const align = paragraphs[0]?.element(A.pPr)?.attribute("algn")?.value;
  if (align && ALIGN_FROM_OOXML[align]) {
    content.align = ALIGN_FROM_OOXML[align];
  }
  const runProps = paragraphs[0]?.element(A.r)?.element(A.rPr);
  if (runProps) {
    const size = runProps.attribute("sz")?.value;
    if (size) {
      content.fontSize = Math.round(Number(size) / 100);
    }
    content.bold = runProps.attribute("b")?.value === "1";
    content.italic = runProps.attribute("i")?.value === "1";
    content.color = solidFillColor(runProps) ?? content.color;
  }
  return content;
}

function parseShape(sp: XElement): ShapeObject | TextObject {
  const nv = sp.element(P.nvSpPr);
  const name = nv?.element(P.cNvPr)?.attribute("name")?.value ?? "図形";
  const isTextBox = nv?.element(P.cNvSpPr)?.attribute("txBox")?.value === "1";
  const spPr = sp.element(P.spPr);
  const frame = parseXfrm(spPr?.element(A.xfrm), `図形「${name}」`);
  const text = parseTextContent(sp.element(P.txBody));

  if (isTextBox) {
    return { id: createId("object"), name, type: "text", ...frame, text };
  }

  const prst = spPr?.element(A.prstGeom)?.attribute("prst")?.value ?? "";
  const kind = PRST_TO_SHAPE_KIND.get(prst);
  if (!kind) {
    throw new PptxImportError(`${UNSUPPORTED_FILE} (未対応の図形タイプ: ${prst || "不明"})`);
  }
  const line = spPr?.element(A.ln);
  return {
    id: createId("object"),
    name,
    type: "shape",
    shape: kind,
    ...frame,
    fill: solidFillColor(spPr) ?? "#ffffff",
    outlineColor: (line ? solidFillColor(line) : undefined) ?? "#000000",
    outlineWidth: line ? emuToPx(line.attribute("w")?.value) : 0,
    text,
  };
}

function chartFromMeta(meta: string, frame: ParsedFrame, context: string): ChartObject {
  let parsed: ChartObject;
  try {
    parsed = JSON.parse(meta) as ChartObject;
  } catch {
    throw new PptxImportError(`${UNSUPPORTED_FILE} (${context} のメタデータを解析できません)`);
  }
  if (parsed.type !== "chart" || !parsed.chartType || !Array.isArray(parsed.series)) {
    throw new PptxImportError(`${UNSUPPORTED_FILE} (${context} のメタデータが不正です)`);
  }
  // The live slide geometry wins over the snapshot in the metadata, so a
  // chart moved/resized in PowerPoint comes back where the user put it.
  return { ...parsed, ...frame };
}

function parseChartFrame(graphicFrame: XElement): ChartObject {
  const cNvPr = graphicFrame.element(P.nvGraphicFramePr)?.element(P.cNvPr);
  const name = cNvPr?.attribute("name")?.value ?? "グラフ";
  const frame = parseXfrm(graphicFrame.element(P.xfrm), `グラフ「${name}」`);
  const meta = cNvPr && readChartMeta(cNvPr);
  if (!meta) {
    throw new PptxImportError(
      `${UNSUPPORTED_FILE} (グラフ「${name}」に再編集用メタデータがありません)`,
    );
  }
  return chartFromMeta(meta, frame, `グラフ「${name}」`);
}

async function readPartBytes(part: OpenXmlPart): Promise<Uint8Array> {
  const data = part.getData();
  if (typeof data === "string") {
    return base64ToBytes(data);
  }
  return (data as { async(type: "uint8array"): Promise<Uint8Array> }).async("uint8array");
}

async function parseChartPic(
  pic: XElement,
  relTargets: ReadonlyMap<string, string>,
  pkg: PmlPackage,
): Promise<ChartObject> {
  const cNvPr = pic.element(P.nvPicPr)?.element(P.cNvPr);
  const name = cNvPr?.attribute("name")?.value ?? "グラフ画像";
  const frame = parseXfrm(pic.element(P.spPr)?.element(A.xfrm), `画像「${name}」`);

  let meta = cNvPr && readChartMeta(cNvPr);
  if (!meta) {
    // Fallback: the PNG itself carries the same JSON in an iTXt chunk.
    const embedId = pic.element(P.blipFill)?.element(A.blip)?.attribute(R.embed)?.value;
    const target = embedId ? relTargets.get(embedId) : undefined;
    const mediaPart = target ? pkg.getPartByUri(target) : undefined;
    if (mediaPart) {
      meta = readPngTextChunk(await readPartBytes(mediaPart), PNG_TEXT_KEYWORD);
    }
  }
  if (!meta) {
    throw new PptxImportError(
      `${UNSUPPORTED_FILE} (画像「${name}」に再編集用メタデータがありません)`,
    );
  }
  const chart = chartFromMeta(meta, frame, `画像「${name}」`);
  return { ...chart, exportAsImage: true };
}

async function parseLeaf(
  element: XElement,
  relTargets: ReadonlyMap<string, string>,
  pkg: PmlPackage,
): Promise<LeafObject> {
  if (element.name === P.sp) {
    return parseShape(element);
  }
  if (element.name === P.graphicFrame) {
    return parseChartFrame(element);
  }
  if (element.name === P.pic) {
    return parseChartPic(element, relTargets, pkg);
  }
  throw new PptxImportError(`${UNSUPPORTED_FILE} (未対応の要素: ${element.name.localName})`);
}

async function parseGroup(
  grpSp: XElement,
  relTargets: ReadonlyMap<string, string>,
  pkg: PmlPackage,
): Promise<GroupObject> {
  const name = grpSp.element(P.nvGrpSpPr)?.element(P.cNvPr)?.attribute("name")?.value ?? "グループ";
  const frame = parseXfrm(grpSp.element(P.grpSpPr)?.element(A.xfrm), `グループ「${name}」`);
  const children: LeafObject[] = [];
  for (const child of grpSp.elements()) {
    if (child.name === P.nvGrpSpPr || child.name === P.grpSpPr) {
      continue;
    }
    // Child coordinates are absolute (the exporter writes chOff == off).
    children.push(await parseLeaf(child, relTargets, pkg));
  }
  return { id: createId("object"), name, type: "group", ...frame, children };
}

async function parseSlide(
  slidePart: OpenXmlPart,
  relTargets: ReadonlyMap<string, string>,
  pkg: PmlPackage,
): Promise<Slide> {
  const root = (await slidePart.getXDocument()).root!;
  const cSld = root.element(P.cSld);
  const background = solidFillColor(cSld?.element(P.bg)?.element(P.bgPr)) ?? "#ffffff";

  const objects: SlideObject[] = [];
  for (const child of cSld?.element(P.spTree)?.elements() ?? []) {
    if (child.name === P.nvGrpSpPr || child.name === P.grpSpPr) {
      continue;
    }
    if (child.name === P.grpSp) {
      objects.push(await parseGroup(child, relTargets, pkg));
    } else {
      objects.push(await parseLeaf(child, relTargets, pkg));
    }
  }
  return { id: createId("slide"), background, objects };
}

export async function deckFromPptxBlob(blob: Blob): Promise<Deck> {
  let pkg: PmlPackage;
  try {
    pkg = await PmlPackage.open(blob);
  } catch {
    throw new PptxImportError("PPTX ファイルとして開けませんでした");
  }

  const presentationPart = await pkg.presentationPart();
  if (!presentationPart) {
    throw new PptxImportError(
      "PPTX ファイルとして開けませんでした (presentation パートがありません)",
    );
  }

  const title =
    (await pkg.coreFilePropertiesPart().then((part) => part?.getXDocument()))?.root?.element(
      DC.title,
    )?.value || "Untitled presentation";

  // Resolve slides in sldIdLst order (slide part order in the package is
  // not guaranteed to match the presentation order).
  const presentationRels = new Map(
    (await pkg.getRelationshipsForPart(presentationPart)).map((rel) => [
      rel.getId(),
      rel.getTargetFullName(),
    ]),
  );
  const presentationRoot = (await presentationPart.getXDocument()).root!;
  const slideIds = presentationRoot
    .element(P.sldIdLst)
    ?.elements(P.sldId)
    .map((sldId) => sldId.attribute(R.id)?.value)
    .filter((id): id is string => Boolean(id));

  const slides: Slide[] = [];
  for (const relId of slideIds ?? []) {
    const target = presentationRels.get(relId);
    const slidePart = target ? pkg.getPartByUri(target) : undefined;
    if (!slidePart) {
      continue;
    }
    const relTargets = new Map(
      (await pkg.getRelationshipsForPart(slidePart)).map((rel) => [
        rel.getId(),
        rel.getTargetFullName(),
      ]),
    );
    slides.push(await parseSlide(slidePart, relTargets, pkg));
  }

  return { title, slides: slides.length > 0 ? slides : [createSlide()] };
}
