/**
 * Reads a .pptx generated by this app back into the editor model.
 *
 * Shapes, text boxes and groups are parsed from the slide OOXML (the subset
 * the exporter emits). Charts are restored from the re-edit metadata that
 * rides on each chart: the `a:extLst` on the shape's `p:cNvPr` (primary),
 * or — for image-exported charts — the iTXt chunk inside the PNG itself.
 */
import { A, DC, P, PmlPackage, R, XElement, type OpenXmlPart } from "openxmlsdkts";

import { fontKeyFromTypeface, type ResolvedCharStyle } from "@/features/editor/fonts";
import { SHAPE_DEFINITIONS } from "@/features/editor/shape-defs";
import {
  createId,
  createSlide,
  createTextContent,
  type CharStyle,
  type ChartObject,
  type ConnectionSite,
  type ConnectorObject,
  type Deck,
  type GroupObject,
  type LeafObject,
  type ShapeKind,
  type ShapeObject,
  type Slide,
  type SlideObject,
  type TextContent,
  type TextHAlign,
  type TextObject,
  type TextVAlign,
} from "@/features/editor/types";

import { base64ToBytes } from "./binary";
import { readPngTextChunk } from "./png-text";
import { EMU_PER_PX } from "./pptx";
import { PNG_TEXT_KEYWORD, readChartMeta } from "./pptx/chart-meta";

export class PptxImportError extends Error {}

const UNSUPPORTED_FILE = "このアプリで書き出した PPTX ファイルのみ読み込めます";

function emuToPx(value: string | undefined): number {
  return Math.round(Number(value ?? 0) / EMU_PER_PX);
}

const PRST_TO_SHAPE_KIND = new Map<string, ShapeKind>(
  SHAPE_DEFINITIONS.map((definition) => [definition.presetGeometry, definition.kind]),
);

const ALIGN_FROM_OOXML: Record<string, TextHAlign> = {
  l: "left",
  ctr: "center",
  r: "right",
  just: "justify",
};

const ANCHOR_FROM_OOXML: Record<string, TextVAlign> = {
  t: "top",
  ctr: "center",
  b: "bottom",
};

/** Connection-site index → cardinal site (matches the exporter's table). */
const INDEX_TO_SITE: readonly ConnectionSite[] = ["top", "left", "bottom", "right"];

/**
 * Numeric `p:cNvPr@id` → restored editor object id, per slide. Connectors
 * reference their endpoints through these numeric ids.
 */
type ShapeIdRegistry = Map<string, string>;

function registerShapeId(
  registry: ShapeIdRegistry,
  cNvPr: XElement | null | undefined,
  editorId: string,
): void {
  const numericId = cNvPr?.attribute("id")?.value;
  if (numericId) {
    registry.set(numericId, editorId);
  }
}

function hexColor(srgbClr: XElement | null | undefined): string | undefined {
  const value = srgbClr?.attribute("val")?.value;
  return value ? `#${value.toLowerCase()}` : undefined;
}

function solidFillColor(container: XElement | null | undefined): string | undefined {
  return hexColor(container?.element(A.solidFill)?.element(A.srgbClr));
}

interface ParsedFrame {
  x: number;
  y: number;
  width: number;
  height: number;
}

function parseXfrm(xfrm: XElement | null | undefined, context: string): ParsedFrame {
  const off = xfrm?.element(A.off);
  const ext = xfrm?.element(A.ext);
  if (!off || !ext) {
    throw new PptxImportError(`${UNSUPPORTED_FILE} (${context} の座標情報がありません)`);
  }
  return {
    x: emuToPx(off.attribute("x")?.value),
    y: emuToPx(off.attribute("y")?.value),
    width: emuToPx(ext.attribute("cx")?.value),
    height: emuToPx(ext.attribute("cy")?.value),
  };
}

function parseTextContent(txBody: XElement | null | undefined): TextContent {
  const content = createTextContent();
  if (!txBody) {
    return content;
  }
  const anchor = txBody.element(A.bodyPr)?.attribute("anchor")?.value;
  if (anchor && ANCHOR_FROM_OOXML[anchor]) {
    content.verticalAlign = ANCHOR_FROM_OOXML[anchor];
  }
  const paragraphs = txBody.elements(A.p);

  const align = paragraphs[0]?.element(A.pPr)?.attribute("algn")?.value;
  if (align && ALIGN_FROM_OOXML[align]) {
    content.align = ALIGN_FROM_OOXML[align];
  }

  // The first run defines the base style; every other run's style becomes a
  // per-character override where it differs (the exporter writes one run per
  // consecutive same-style segment).
  const readRunStyle = (rPr: XElement | null | undefined): ResolvedCharStyle => {
    const size = rPr?.attribute("sz")?.value;
    return {
      fontFamily: fontKeyFromTypeface(rPr?.element(A.latin)?.attribute("typeface")?.value),
      fontSize: size ? Math.round(Number(size) / 100) : content.fontSize,
      bold: rPr?.attribute("b")?.value === "1",
      italic: rPr?.attribute("i")?.value === "1",
      color: (rPr ? solidFillColor(rPr) : undefined) ?? content.color,
    };
  };

  const firstRunProps = paragraphs[0]?.element(A.r)?.element(A.rPr);
  if (firstRunProps) {
    const base = readRunStyle(firstRunProps);
    content.fontSize = base.fontSize;
    content.bold = base.bold;
    content.italic = base.italic;
    content.color = base.color;
    content.fontFamily = base.fontFamily;
  }

  let text = "";
  const charStyles: (CharStyle | null)[] = [];
  paragraphs.forEach((paragraph, paragraphIndex) => {
    if (paragraphIndex > 0) {
      text += "\n";
      charStyles.push(null);
    }
    for (const run of paragraph.elements(A.r)) {
      const runText = run.element(A.t)?.value ?? "";
      const style = readRunStyle(run.element(A.rPr));
      const override: CharStyle = {};
      if (style.fontFamily !== content.fontFamily) {
        // null = explicit theme default (differs from the base family).
        override.fontFamily = style.fontFamily ?? null;
      }
      if (style.fontSize !== content.fontSize) {
        override.fontSize = style.fontSize;
      }
      if (style.color !== content.color) {
        override.color = style.color;
      }
      if (style.bold !== content.bold) {
        override.bold = style.bold;
      }
      if (style.italic !== content.italic) {
        override.italic = style.italic;
      }
      const entry = Object.keys(override).length > 0 ? override : null;
      text += runText;
      for (let index = 0; index < runText.length; index += 1) {
        charStyles.push(entry);
      }
    }
  });
  // The exporter writes a single empty paragraph for empty text.
  content.text = text.replace(/^\n?$/, "");
  if (content.text && charStyles.slice(0, content.text.length).some((style) => style !== null)) {
    content.charStyles = charStyles.slice(0, content.text.length);
  }
  return content;
}

function parseShape(sp: XElement, registry: ShapeIdRegistry): ShapeObject | TextObject {
  const nv = sp.element(P.nvSpPr);
  const cNvPr = nv?.element(P.cNvPr);
  const name = cNvPr?.attribute("name")?.value ?? "図形";
  const isTextBox = nv?.element(P.cNvSpPr)?.attribute("txBox")?.value === "1";
  const spPr = sp.element(P.spPr);
  const frame = parseXfrm(spPr?.element(A.xfrm), `図形「${name}」`);
  const text = parseTextContent(sp.element(P.txBody));
  const id = createId("object");
  registerShapeId(registry, cNvPr, id);

  if (isTextBox) {
    return { id, name, type: "text", ...frame, text };
  }

  const prst = spPr?.element(A.prstGeom)?.attribute("prst")?.value ?? "";
  const kind = PRST_TO_SHAPE_KIND.get(prst);
  if (!kind) {
    throw new PptxImportError(`${UNSUPPORTED_FILE} (未対応の図形タイプ: ${prst || "不明"})`);
  }
  const line = spPr?.element(A.ln);
  return {
    id,
    name,
    type: "shape",
    shape: kind,
    ...frame,
    fill: solidFillColor(spPr) ?? "#ffffff",
    outlineColor: (line ? solidFillColor(line) : undefined) ?? "#000000",
    outlineWidth: line ? emuToPx(line.attribute("w")?.value) : 0,
    text,
  };
}

function chartFromMeta(meta: string, frame: ParsedFrame, context: string): ChartObject {
  let parsed: ChartObject;
  try {
    parsed = JSON.parse(meta) as ChartObject;
  } catch {
    throw new PptxImportError(`${UNSUPPORTED_FILE} (${context} のメタデータを解析できません)`);
  }
  if (parsed.type !== "chart" || !parsed.chartType || !Array.isArray(parsed.series)) {
    throw new PptxImportError(`${UNSUPPORTED_FILE} (${context} のメタデータが不正です)`);
  }
  // The live slide geometry wins over the snapshot in the metadata, so a
  // chart moved/resized in PowerPoint comes back where the user put it.
  return { ...parsed, ...frame };
}

function parseChartFrame(graphicFrame: XElement, registry: ShapeIdRegistry): ChartObject {
  const cNvPr = graphicFrame.element(P.nvGraphicFramePr)?.element(P.cNvPr);
  const name = cNvPr?.attribute("name")?.value ?? "グラフ";
  const frame = parseXfrm(graphicFrame.element(P.xfrm), `グラフ「${name}」`);
  const meta = cNvPr && readChartMeta(cNvPr);
  if (!meta) {
    throw new PptxImportError(
      `${UNSUPPORTED_FILE} (グラフ「${name}」に再編集用メタデータがありません)`,
    );
  }
  const chart = chartFromMeta(meta, frame, `グラフ「${name}」`);
  registerShapeId(registry, cNvPr, chart.id);
  return chart;
}

async function readPartBytes(part: OpenXmlPart): Promise<Uint8Array> {
  const data = part.getData();
  if (typeof data === "string") {
    return base64ToBytes(data);
  }
  return (data as { async(type: "uint8array"): Promise<Uint8Array> }).async("uint8array");
}

async function parseChartPic(
  pic: XElement,
  relTargets: ReadonlyMap<string, string>,
  pkg: PmlPackage,
  registry: ShapeIdRegistry,
): Promise<ChartObject> {
  const cNvPr = pic.element(P.nvPicPr)?.element(P.cNvPr);
  const name = cNvPr?.attribute("name")?.value ?? "グラフ画像";
  const frame = parseXfrm(pic.element(P.spPr)?.element(A.xfrm), `画像「${name}」`);

  let meta = cNvPr && readChartMeta(cNvPr);
  if (!meta) {
    // Fallback: the PNG itself carries the same JSON in an iTXt chunk.
    const embedId = pic.element(P.blipFill)?.element(A.blip)?.attribute(R.embed)?.value;
    const target = embedId ? relTargets.get(embedId) : undefined;
    const mediaPart = target ? pkg.getPartByUri(target) : undefined;
    if (mediaPart) {
      meta = readPngTextChunk(await readPartBytes(mediaPart), PNG_TEXT_KEYWORD);
    }
  }
  if (!meta) {
    throw new PptxImportError(
      `${UNSUPPORTED_FILE} (画像「${name}」に再編集用メタデータがありません)`,
    );
  }
  const chart = chartFromMeta(meta, frame, `画像「${name}」`);
  registerShapeId(registry, cNvPr, chart.id);
  return { ...chart, exportAsImage: true };
}

/**
 * `p:cxnSp` → ConnectorObject. Endpoints are restored from the semantic
 * `a:stCxn`/`a:endCxn` references (numeric shape id + site index), the
 * concrete geometry from the xfrm (off/ext + flips).
 */
function parseConnector(cxnSp: XElement, registry: ShapeIdRegistry): ConnectorObject {
  const nv = cxnSp.element(P.nvCxnSpPr);
  const name = nv?.element(P.cNvPr)?.attribute("name")?.value ?? "コネクタ";
  const context = `コネクタ「${name}」`;

  const readEndpoint = (elementName: typeof A.stCxn): ConnectorObject["start"] => {
    const reference = nv?.element(P.cNvCxnSpPr)?.element(elementName);
    const numericId = reference?.attribute("id")?.value;
    const site = INDEX_TO_SITE[Number(reference?.attribute("idx")?.value ?? -1)];
    const objectId = numericId ? registry.get(numericId) : undefined;
    if (!objectId || !site) {
      throw new PptxImportError(`${UNSUPPORTED_FILE} (${context} の接続先を解決できません)`);
    }
    return { objectId, site };
  };

  const spPr = cxnSp.element(P.spPr);
  const xfrmElement = spPr?.element(A.xfrm);
  const frame = parseXfrm(xfrmElement, context);
  const flipH = xfrmElement?.attribute("flipH")?.value === "1";
  const flipV = xfrmElement?.attribute("flipV")?.value === "1";

  const prst = spPr?.element(A.prstGeom)?.attribute("prst")?.value;
  const connectorType =
    prst === "bentConnector3" ? "bent" : prst === "straightConnector1" ? "straight" : undefined;
  if (!connectorType) {
    throw new PptxImportError(`${UNSUPPORTED_FILE} (未対応のコネクタ: ${prst ?? "不明"})`);
  }

  const line = spPr?.element(A.ln);
  const tailType = line?.element(A.tailEnd)?.attribute("type")?.value;

  return {
    id: createId("object"),
    name,
    type: "connector",
    connectorType,
    start: readEndpoint(A.stCxn),
    end: readEndpoint(A.endCxn),
    startPoint: {
      x: flipH ? frame.x + frame.width : frame.x,
      y: flipV ? frame.y + frame.height : frame.y,
    },
    endPoint: {
      x: flipH ? frame.x : frame.x + frame.width,
      y: flipV ? frame.y : frame.y + frame.height,
    },
    ...frame,
    lineColor: (line ? solidFillColor(line) : undefined) ?? "#1f2937",
    lineWidth: line ? Math.max(1, emuToPx(line.attribute("w")?.value)) : 1,
    arrowEnd: tailType !== undefined && tailType !== "none",
  };
}

async function parseLeaf(
  element: XElement,
  relTargets: ReadonlyMap<string, string>,
  pkg: PmlPackage,
  registry: ShapeIdRegistry,
): Promise<LeafObject> {
  if (element.name === P.sp) {
    return parseShape(element, registry);
  }
  if (element.name === P.graphicFrame) {
    return parseChartFrame(element, registry);
  }
  if (element.name === P.pic) {
    return parseChartPic(element, relTargets, pkg, registry);
  }
  throw new PptxImportError(`${UNSUPPORTED_FILE} (未対応の要素: ${element.name.localName})`);
}

async function parseGroup(
  grpSp: XElement,
  relTargets: ReadonlyMap<string, string>,
  pkg: PmlPackage,
  registry: ShapeIdRegistry,
): Promise<GroupObject> {
  const cNvPr = grpSp.element(P.nvGrpSpPr)?.element(P.cNvPr);
  const name = cNvPr?.attribute("name")?.value ?? "グループ";
  const frame = parseXfrm(grpSp.element(P.grpSpPr)?.element(A.xfrm), `グループ「${name}」`);
  const children: SlideObject[] = [];
  for (const child of grpSp.elements()) {
    if (child.name === P.nvGrpSpPr || child.name === P.grpSpPr) {
      continue;
    }
    // Child coordinates are absolute (the exporter writes chOff == off at
    // every level), so nested groups parse with the same recursion.
    if (child.name === P.grpSp) {
      children.push(await parseGroup(child, relTargets, pkg, registry));
    } else {
      children.push(await parseLeaf(child, relTargets, pkg, registry));
    }
  }
  const id = createId("object");
  registerShapeId(registry, cNvPr, id);
  return { id, name, type: "group", ...frame, children };
}

async function parseSlide(
  slidePart: OpenXmlPart,
  relTargets: ReadonlyMap<string, string>,
  pkg: PmlPackage,
): Promise<Slide> {
  const root = (await slidePart.getXDocument()).root!;
  const cSld = root.element(P.cSld);
  const background = solidFillColor(cSld?.element(P.bg)?.element(P.bgPr)) ?? "#ffffff";

  // Two-phase parse: connectors reference other shapes by numeric id, and
  // may precede their endpoints in z-order, so they resolve after every
  // other object has been parsed (order is preserved).
  const registry: ShapeIdRegistry = new Map();
  const ordered: (SlideObject | { pendingConnector: XElement })[] = [];
  for (const child of cSld?.element(P.spTree)?.elements() ?? []) {
    if (child.name === P.nvGrpSpPr || child.name === P.grpSpPr) {
      continue;
    }
    if (child.name === P.cxnSp) {
      ordered.push({ pendingConnector: child });
    } else if (child.name === P.grpSp) {
      ordered.push(await parseGroup(child, relTargets, pkg, registry));
    } else {
      ordered.push(await parseLeaf(child, relTargets, pkg, registry));
    }
  }
  const objects: SlideObject[] = ordered.map((entry) =>
    "pendingConnector" in entry ? parseConnector(entry.pendingConnector, registry) : entry,
  );
  return { id: createId("slide"), background, objects };
}

export async function deckFromPptxBlob(blob: Blob): Promise<Deck> {
  let pkg: PmlPackage;
  try {
    pkg = await PmlPackage.open(blob);
  } catch {
    throw new PptxImportError("PPTX ファイルとして開けませんでした");
  }

  const presentationPart = await pkg.presentationPart();
  if (!presentationPart) {
    throw new PptxImportError(
      "PPTX ファイルとして開けませんでした (presentation パートがありません)",
    );
  }

  const title =
    (await pkg.coreFilePropertiesPart().then((part) => part?.getXDocument()))?.root?.element(
      DC.title,
    )?.value || "Untitled presentation";

  // Resolve slides in sldIdLst order (slide part order in the package is
  // not guaranteed to match the presentation order).
  const presentationRels = new Map(
    (await pkg.getRelationshipsForPart(presentationPart)).map((rel) => [
      rel.getId(),
      rel.getTargetFullName(),
    ]),
  );
  const presentationRoot = (await presentationPart.getXDocument()).root!;
  const slideIds = presentationRoot
    .element(P.sldIdLst)
    ?.elements(P.sldId)
    .map((sldId) => sldId.attribute(R.id)?.value)
    .filter((id): id is string => Boolean(id));

  const slides: Slide[] = [];
  for (const relId of slideIds ?? []) {
    const target = presentationRels.get(relId);
    const slidePart = target ? pkg.getPartByUri(target) : undefined;
    if (!slidePart) {
      continue;
    }
    const relTargets = new Map(
      (await pkg.getRelationshipsForPart(slidePart)).map((rel) => [
        rel.getId(),
        rel.getTargetFullName(),
      ]),
    );
    slides.push(await parseSlide(slidePart, relTargets, pkg));
  }

  return { title, slides: slides.length > 0 ? slides : [createSlide()] };
}
